switch(GetPVarInt(playerid,"RazdelMebel")) {
	case 0:
	{
        switch(cskin[playerid]) {
        case 0: { SetPVarInt(playerid,"MebelItem",2370); }
        case 1: { SetPVarInt(playerid,"MebelItem",2356); }
	    case 2: { SetPVarInt(playerid,"MebelItem",2357); }
	    case 3: { SetPVarInt(playerid,"MebelItem",2725); }
	    case 4: { SetPVarInt(playerid,"MebelItem",2576); }
	    case 5: { SetPVarInt(playerid,"MebelItem",2310); }
	    case 6: { SetPVarInt(playerid,"MebelItem",2313); }
	    case 7: { SetPVarInt(playerid,"MebelItem",2319); }
	    case 8: { SetPVarInt(playerid,"MebelItem",2323); }
	    case 9: { SetPVarInt(playerid,"MebelItem",2330); }
	    case 10: { SetPVarInt(playerid,"MebelItem",2337); }
	    case 11: { SetPVarInt(playerid,"MebelItem",2338); }
	    case 12: { SetPVarInt(playerid,"MebelItem",2339); }
	    case 13: { SetPVarInt(playerid,"MebelItem",2340); }
	    case 14: { SetPVarInt(playerid,"MebelItem",2346); }
	    case 15: { SetPVarInt(playerid,"MebelItem",2350); }
	    case 16: { SetPVarInt(playerid,"MebelItem",2563); }
	    case 17: { SetPVarInt(playerid,"MebelItem",2575); }
	    case 18: { SetPVarInt(playerid,"MebelItem",2297); }
	    case 19: { SetPVarInt(playerid,"MebelItem",2296); }
	    case 20: { SetPVarInt(playerid,"MebelItem",1712); }
	    case 21: { SetPVarInt(playerid,"MebelItem",1711); }
	    case 22: { SetPVarInt(playerid,"MebelItem",1710); }
	    case 23: { SetPVarInt(playerid,"MebelItem",1709); }
	    case 24: { SetPVarInt(playerid,"MebelItem",1708); }
	    case 25: { SetPVarInt(playerid,"MebelItem",1707); }
	    case 26: { SetPVarInt(playerid,"MebelItem",1706); }
	    case 27: { SetPVarInt(playerid,"MebelItem",1705); }
	    case 28: { SetPVarInt(playerid,"MebelItem",1704); }
	    case 29: { SetPVarInt(playerid,"MebelItem",1703); }
	    case 30: { SetPVarInt(playerid,"MebelItem",1702); }
	    case 31: { SetPVarInt(playerid,"MebelItem",1701); }
	    case 32: { SetPVarInt(playerid,"MebelItem",1700); }
	    case 33: { SetPVarInt(playerid,"MebelItem",1726); }
	    case 34: { SetPVarInt(playerid,"MebelItem",1725); }
	    case 35: { SetPVarInt(playerid,"MebelItem",1722); }
	    case 36: { SetPVarInt(playerid,"MebelItem",1720); }
	    case 37: { SetPVarInt(playerid,"MebelItem",1716); }
	    case 38: { SetPVarInt(playerid,"MebelItem",1714); }
	    case 39: { SetPVarInt(playerid,"MebelItem",1713); }
	    case 40: { SetPVarInt(playerid,"MebelItem",1765); }
	    case 41: { SetPVarInt(playerid,"MebelItem",1764); }
	    case 42: { SetPVarInt(playerid,"MebelItem",1815); }
		case 43: { SetPVarInt(playerid,"MebelItem",2299); }
		case 44: { SetPVarInt(playerid,"MebelItem",2239); }
		case 45: { SetPVarInt(playerid,"MebelItem",2206); }
		case 46: { SetPVarInt(playerid,"MebelItem",2210); }
		case 47: { SetPVarInt(playerid,"MebelItem",2205); }
		case 48: { SetPVarInt(playerid,"MebelItem",2204); }
		case 49: { SetPVarInt(playerid,"MebelItem",2208); }
		case 50: { SetPVarInt(playerid,"MebelItem",2069); }
        case 51: { SetPVarInt(playerid,"MebelItem",2026); } }
	}
	case 1:
	{
	    //Двери
	    switch(cskin[playerid]) {
	    case 0: { SetPVarInt(playerid,"MebelItem",1502); }
	    case 1: { SetPVarInt(playerid,"MebelItem",1494); }
	    case 2: { SetPVarInt(playerid,"MebelItem",1492); }
	    case 3: { SetPVarInt(playerid,"MebelItem",1491); }
	    case 4: { SetPVarInt(playerid,"MebelItem",1535); }
	    case 5: { SetPVarInt(playerid,"MebelItem",1507); }
	    case 6: { SetPVarInt(playerid,"MebelItem",1506); }
	    case 7: { SetPVarInt(playerid,"MebelItem",1504); }
	    case 8: { SetPVarInt(playerid,"MebelItem",1503); } }
	}
	case 2:
	{
	    //Картины
	    switch(cskin[playerid]) {
	    case 0: { SetPVarInt(playerid,"MebelItem",2289); }
	    case 1: { SetPVarInt(playerid,"MebelItem",2287); }
	    case 2: { SetPVarInt(playerid,"MebelItem",2286); }
	    case 3: { SetPVarInt(playerid,"MebelItem",2285); }
	    case 4: { SetPVarInt(playerid,"MebelItem",2284); }
	    case 5: { SetPVarInt(playerid,"MebelItem",2283); }
	    case 6: { SetPVarInt(playerid,"MebelItem",2282); }
	    case 7: { SetPVarInt(playerid,"MebelItem",2281); }
        case 8: { SetPVarInt(playerid,"MebelItem",2280); }
	    case 9: { SetPVarInt(playerid,"MebelItem",2279); }
	    case 10: { SetPVarInt(playerid,"MebelItem",2278); }
	    case 11: { SetPVarInt(playerid,"MebelItem",2277); }
	    case 12: { SetPVarInt(playerid,"MebelItem",2276); } }
	}
	case 3:
	{
        //Цветы домашние
        switch(cskin[playerid]) {
        case 0: { SetPVarInt(playerid,"MebelItem",949); }
        case 1: { SetPVarInt(playerid,"MebelItem",2253); }
        case 2: { SetPVarInt(playerid,"MebelItem",2252); }
        case 3: { SetPVarInt(playerid,"MebelItem",2251); }
        case 4: { SetPVarInt(playerid,"MebelItem",2250); }
        case 5: { SetPVarInt(playerid,"MebelItem",2249); }
        case 6: { SetPVarInt(playerid,"MebelItem",2245); }
        case 7: { SetPVarInt(playerid,"MebelItem",2244); }
        case 8: { SetPVarInt(playerid,"MebelItem",2241); }
        case 9: { SetPVarInt(playerid,"MebelItem",2240); }
        case 10: { SetPVarInt(playerid,"MebelItem",2023); } }
	}
	case 4:
	{
		//Техника для дома
	    switch(cskin[playerid]) {
	    case 0: { SetPVarInt(playerid,"MebelItem",2421); }
	    case 1: { SetPVarInt(playerid,"MebelItem",2750); }
	    case 2: { SetPVarInt(playerid,"MebelItem",2595); }
	    case 3: { SetPVarInt(playerid,"MebelItem",2322); }
	    case 4: { SetPVarInt(playerid,"MebelItem",2320); }
	    case 5: { SetPVarInt(playerid,"MebelItem",2316); }
	    case 6: { SetPVarInt(playerid,"MebelItem",2233); }
	    case 7: { SetPVarInt(playerid,"MebelItem",2232); }
	    case 8: { SetPVarInt(playerid,"MebelItem",2231); }
	    case 9: { SetPVarInt(playerid,"MebelItem",2230); }
	    case 10: { SetPVarInt(playerid,"MebelItem",2229); }
	    case 11: { SetPVarInt(playerid,"MebelItem",2227); }
	    case 12: { SetPVarInt(playerid,"MebelItem",2226); }
	    case 13: { SetPVarInt(playerid,"MebelItem",2225); }
	    case 14: { SetPVarInt(playerid,"MebelItem",2104); }
	    case 15: { SetPVarInt(playerid,"MebelItem",2103); }
	    case 16: { SetPVarInt(playerid,"MebelItem",2099); }
	    case 17: { SetPVarInt(playerid,"MebelItem",1809); }
	    case 18: { SetPVarInt(playerid,"MebelItem",1717); }
	    case 19: { SetPVarInt(playerid,"MebelItem",1518); } }
	}
	case 5:
	{
		//Всё для ванной
	    switch(cskin[playerid]) {
	    case 0: { SetPVarInt(playerid,"MebelItem",2097); }
	    case 1: { SetPVarInt(playerid,"MebelItem",2517); }
	    case 2: { SetPVarInt(playerid,"MebelItem",2516); }
	    case 3: { SetPVarInt(playerid,"MebelItem",2515); }
	    case 4: { SetPVarInt(playerid,"MebelItem",2514); }
	    case 5: { SetPVarInt(playerid,"MebelItem",2518); }
	    case 6: { SetPVarInt(playerid,"MebelItem",2519); }
	    case 7: { SetPVarInt(playerid,"MebelItem",2520); }
	    case 8: { SetPVarInt(playerid,"MebelItem",2521); }
	    case 9: { SetPVarInt(playerid,"MebelItem",2522); }
	    case 10: { SetPVarInt(playerid,"MebelItem",2523); }
	    case 11: { SetPVarInt(playerid,"MebelItem",2524); }
	    case 12: { SetPVarInt(playerid,"MebelItem",2525); }
	    case 13: { SetPVarInt(playerid,"MebelItem",2526); }
	    case 14: { SetPVarInt(playerid,"MebelItem",2527); }
	    case 15: { SetPVarInt(playerid,"MebelItem",2528); } }
	} }